services:
  nginx:
    image: nginx:stable-alpine-slim
    container_name: local_directory
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htdocs:/var/www:ro
